version: 2
jobs:
   build:
     docker:
       - image: buildpack-deps:trusty
       - image: circleci/java:8
       - image: maven/3.5.0-jdk-7
     steps:
       - checkout
       - run: echo "hello world"
       - run: mvn compile

