version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8-jdk-browsers
       - image: buildpack-deps:trusty
       - image: circleci/java:8
     steps:
       - checkout
       - run: echo "hello world"
       - run: mvn compile

